import { NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';

/**
 * /api/passport — read and manage the signed-in user's own passport.
 *
 * ## Passport IDs and share slugs are database-owned
 *
 * This route used to mint both values in TypeScript. That is now impossible,
 * and was always wrong:
 *
 * - **passport_id** is generated by `public.generate_passport_id()` and applied
 *   by the `trg_fill_passport` BEFORE INSERT/UPDATE trigger. The format is
 *   `PYF-{5 chars}-{check char}` from a 32-symbol alphabet, validated by
 *   `chk_passport_id_format`. A TypeScript generator writing `PTQ-{CC}-{YYYY}
 *   -{XXXX}` is rejected outright by that constraint on a migrated database,
 *   and its 16 bits of entropy were enumerable.
 * - **passport_share_slug** is allocated only by the `generate_share_slug(uid)`
 *   RPC, which is `security definer` + `auth.uid()`-gated and uses
 *   `gen_random_bytes(5)` (40 bits). The previous local fallback used
 *   `Math.random` and, worse, wrote `is_passport_public = true` as a side
 *   effect of regenerating a slug — publishing a passport the user never
 *   agreed to publish.
 *
 * So: to force reissue, write `passport_id = null` and let the trigger fill
 * it. To allocate or rotate a slug, call the RPC and let it do the UPDATE.
 * Publication is a separate, explicit column write and nothing else touches it.
 */

const NO_STORE = { 'Cache-Control': 'no-store, private' } as const;

const PASSPORT_COLUMNS =
  'id, name, role, country, skills, goals, passport_id, passport_share_slug, is_passport_public, passport_issued_at, onboarding_completed, metadata';

/** Columns returned after a mutation — never `metadata`, which the caller already has. */
const PASSPORT_MUTATION_COLUMNS = 'passport_id, passport_share_slug, is_passport_public, passport_issued_at';

interface ActionBody {
  action?: unknown;
  is_public?: unknown;
}

/**
 * Force a fresh passport ID by nulling the column and letting `trg_fill_passport`
 * allocate a new one. Returns the mutated row, or an error Response.
 */
async function reissuePassportId(supabase: Awaited<ReturnType<typeof createClient>>, userId: string) {
  const { data, error } = await supabase
    .from('user_profiles')
    .update({ passport_id: null, passport_issued_at: new Date().toISOString() })
    .eq('id', userId)
    .select(PASSPORT_MUTATION_COLUMNS)
    .single();

  if (error) return { error: NextResponse.json({ error: error.message }, { status: 500, headers: NO_STORE }) };
  if (!data?.passport_id) {
    return {
      error: NextResponse.json(
        { error: 'Passport could not be reissued. Confirm 20260926_hardening_passport_v2.sql has been applied.' },
        { status: 500, headers: NO_STORE }
      ),
    };
  }
  return { data };
}

export async function GET() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401, headers: NO_STORE });
  }

  const { data, error } = await supabase
    .from('user_profiles')
    .select(PASSPORT_COLUMNS)
    .eq('id', user.id)
    .single();

  if (error) {
    // Degrade gracefully if the extended-passport migration has not run yet,
    // so an unmigrated database shows a usable credential rather than a 500.
    if (looksLikeMissingColumn(error.message)) {
      const { data: stdData, error: stdErr } = await supabase
        .from('user_profiles')
        .select('id, name, role, country, skills, goals, passport_id, passport_share_slug, is_passport_public, passport_issued_at')
        .eq('id', user.id)
        .single();
      if (stdErr) {
        return NextResponse.json({ error: stdErr.message }, { status: 500, headers: NO_STORE });
      }
      return NextResponse.json(
        { ...stdData, onboarding_completed: false, metadata: {} },
        { headers: NO_STORE }
      );
    }
    return NextResponse.json({ error: error.message }, { status: 500, headers: NO_STORE });
  }

  // Self-heal rows created before the trigger existed. Nulling the column is
  // the only supported way to ask for a new ID — see the module comment.
  if (!data.passport_id) {
    const reissued = await reissuePassportId(supabase, user.id);
    if ('error' in reissued) return reissued.error;
    return NextResponse.json({ ...data, ...reissued.data }, { headers: NO_STORE });
  }

  return NextResponse.json(data, { headers: NO_STORE });
}

function looksLikeMissingColumn(message: string): boolean {
  const m = message.toLowerCase();
  return m.includes('metadata') || m.includes('onboarding_completed') || m.includes('column');
}

export async function POST(request: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401, headers: NO_STORE });
  }

  let body: ActionBody = {};
  try {
    body = (await request.json()) as ActionBody;
  } catch {
    body = {};
  }
  const action = typeof body.action === 'string' ? body.action : 'toggle_public';

  if (action === 'toggle_public') {
    const { data: cur, error: readErr } = await supabase
      .from('user_profiles')
      .select('is_passport_public, passport_share_slug')
      .eq('id', user.id)
      .single();
    if (readErr) {
      return NextResponse.json({ error: readErr.message }, { status: 500, headers: NO_STORE });
    }

    const nextPublic = typeof body.is_public === 'boolean' ? body.is_public : !cur?.is_passport_public;

    // Publishing without a slug is impossible: /p/[slug] looks the profile up by
    // slug. Allocate one first, but never as a side effect of *going private*.
    let slug = cur?.passport_share_slug ?? null;
    if (nextPublic && !slug) {
      const allocated = await allocateShareSlug(supabase, user.id);
      if ('error' in allocated) return allocated.error;
      slug = allocated.slug;
    }

    const { data, error } = await supabase
      .from('user_profiles')
      .update({ is_passport_public: nextPublic })
      .eq('id', user.id)
      .select(PASSPORT_MUTATION_COLUMNS)
      .single();
    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500, headers: NO_STORE });
    }

    return NextResponse.json({ ...data, passport_share_slug: data.passport_share_slug ?? slug }, { headers: NO_STORE });
  }

  if (action === 'regenerate_slug') {
    // Rotating the slug must not change publication state. The previous
    // implementation set `is_passport_public = true` here, which meant clicking
    // "new link" silently published the passport.
    const allocated = await allocateShareSlug(supabase, user.id);
    if ('error' in allocated) return allocated.error;

    const { data, error } = await supabase
      .from('user_profiles')
      .select(PASSPORT_MUTATION_COLUMNS)
      .eq('id', user.id)
      .single();
    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500, headers: NO_STORE });
    }

    return NextResponse.json({ ...data, passport_share_slug: allocated.slug }, { headers: NO_STORE });
  }

  if (action === 'regenerate_passport') {
    const reissued = await reissuePassportId(supabase, user.id);
    if ('error' in reissued) return reissued.error;
    return NextResponse.json(reissued.data, { headers: NO_STORE });
  }

  return NextResponse.json({ error: 'Unknown action' }, { status: 400, headers: NO_STORE });
}

/**
 * The single path to a share slug. Delegates entirely to the auth.uid()-gated
 * `generate_share_slug` RPC, which is the only component with permission to
 * allocate one. `uid` is always the caller's own id from the verified session,
 * never anything from the request body.
 */
async function allocateShareSlug(supabase: Awaited<ReturnType<typeof createClient>>, uid: string) {
  const { data, error } = await supabase.rpc('generate_share_slug', { uid });

  if (error) {
    const code = error.code;
    if (code === '42501') {
      return {
        error: NextResponse.json(
          { error: 'You can only rotate your own share link.' },
          { status: 403, headers: NO_STORE }
        ),
      };
    }
    return {
      error: NextResponse.json(
        {
          error: error.message,
          detail:
            'generate_share_slug is missing. Apply supabase/migrations/20260926_hardening_passport_v2.sql.',
        },
        { status: 500, headers: NO_STORE }
      ),
    };
  }

  const slug = typeof data === 'string' ? data : null;
  if (!slug) {
    return {
      error: NextResponse.json(
        { error: 'Could not allocate a share link. Try again.' },
        { status: 500, headers: NO_STORE }
      ),
    };
  }

  return { slug };
}
